version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Use localhost:5433 when using the SSH tunnel
      - DB_HOST=host.docker.internal
      - DB_PORT=5433
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ANTHROPICS_API_KEY=${ANTHROPICS_API_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SESSION_SECRET_KEY=${SESSION_SECRET_KEY}
      - COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
      - COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
      - COGNITO_CLIENT_SECRET=${COGNITO_CLIENT_SECRET}
    volumes:
      - ./app/temp:/app/app/temp
    restart: unless-stopped
