services:
  anova_pg:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5440:5432
  anova_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      DB_HOST: anova_pg
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
      SESSION_SECRET_KEY: ${SESSION_SECRET_KEY}
      ANTHROPICS_API_KEY: ${ANTHROPICS_API_KEY}
    